### ISSUE TITLE
为什么FFM的预测公式采用的FM的化简形式，即求vvxx、vxvx

### ISSUE THREAD

**Issue by cnkuangshi** [xswang/Field-aware-Factorization-Machines-Mpi#2]
RT，不会造成错误么

**Comment by xswang** [comment]
您好，很感谢指出。我看一下这个问题，忘记当时是没实现FFM的inference还是就按照FM的inference公式计算了。

**Comment by cnkuangshi** [comment]
我最近也在做这方面的工作，发现你这种数据并行、梯度汇总的做法（相当于全局GD）很难收敛，跑的000的数据集，并且以LR方式跑，likelihood始终不提升，是否因为这种GD方式就是不太好收敛，并且FTRL也不适应这种全局GD的方案

**Comment by xswang** [comment]
您好~LR和FM的模型是没有问题的，之前用真实数据做过实验。github上的这个数据是其中的一小小部分，也许是由于数据的原因。

在 2017年9月25日 上午11:37，Simon Song <notifications@github.com>写道：

**Comment by xswang** [comment]
另外你看的指标是likelihood，可以观察下logloss的变化情况。

在 2017年9月25日 下午10:51，Xiaoshu Wang <2012wxs@gmail.com>写道：

**Comment by xswang** [comment]
我这里的FFM的实现确实有问题。我后续会把LR，FM，FFM拆开分别实现分别优化。感谢~

**Comment by xswang** [comment]
关于FTRL是否适合这种分布式全局GD，这个是没问题的，我一个朋友已经从理论上证明了这一点儿，等他文章发表您可以参考一下。我和他也仔细讨论过这个问题，理论上是由保证的。
